version: "1.0"
info:
  model: int-scaffold
packages:
- name: KMAT_ListAssets_Jul4Project
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm/KMAT_ListAssets_Jul4Project
  gitUsername: karthikbm
  gitBranch: main
